import { Datum } from "./schemas";

type ApiList = Omit<Datum, "date" | "dataReceived" | "downloadTime">[];

export const apiList: ApiList = [
	{
		apiName: "masterDonors",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstDonor.json",
		queryString: null,
		charts: ["CBPF_by_year"],
		apiType: "master",
	},
	{
		apiName: "masterFunds",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstCountry.json",
		queryString: null,
		charts: ["CBPF_by_year", "Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "masterRegionalFunds",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstRhpf.json",
		queryString: null,
		charts: [
			"Contributions",
			"Allocations",
			"Funding_overview",
			"Gender_with_age_marker",
			"CBPF_vs_HRP",
		],
		apiType: "master",
	},
	{
		apiName: "masterAllocationTypes",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstAllocation.json",
		queryString: null,
		charts: ["CBPF_by_year", "Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "launchedAllocationsData",
		url: "https://cbpfapi.unocha.org/vo2/odata/AllocationTypes",
		queryString: "?PoolfundCodeAbbrv=&$format=csv",
		charts: [
			"CBPF_by_year",
			"Allocation_flow",
			"Allocations",
			"Allocations_timeline",
			"Sectors",
			"Gender_with_age_marker",
		],
		apiType: "data",
	},
	{
		apiName: "contributionsData",
		url: "https://cbpfgms.github.io/pfbi-data/contributionSummarySankey.csv",
		queryString: null,
		charts: ["CBPF_by_year"],
		apiType: "data",
	},
	{
		apiName: "allocationFlowData",
		url: "https://cbpfapi.unocha.org/vo2/odata/AllocationFlowByOrgType",
		queryString: "?PoolfundCodeAbbrv=&$format=csv",
		charts: ["Allocation_flow"],
		apiType: "data",
	},
	{
		apiName: "masterPooledFunds",
		url: "https://cbpfapi.unocha.org/vo2/odata/MstPooledFund",
		queryString: "?$format=csv",
		charts: ["Allocation_flow"],
		apiType: "master",
	},
	{
		apiName: "masterPartners",
		url: "https://cbpfapi.unocha.org/vo2/odata/MstOrgType",
		queryString: "?$format=csv",
		charts: ["Allocation_flow"],
		apiType: "master",
	},
	{
		apiName: "masterSubPartners",
		url: "https://cbpfapi.unocha.org/vo2/odata/SubIPType",
		queryString: "?$format=csv",
		charts: ["Allocation_flow"],
		apiType: "master",
	},
	{
		apiName: "allocationsData",
		url: "https://cbpfapi.unocha.org/vo2/odata/AllocationBudgetTotalsByYearAndFund",
		queryString: "?&FundingType=3&$format=csv",
		charts: ["Allocations"],
		apiType: "data",
	},
	{
		apiName: "contributionsTotalData",
		url: "https://cbpfapi.unocha.org/vo2/odata/ContributionTotal",
		queryString: "?$format=csv&ShowAllPooledFunds=1",
		charts: ["Contributions", "Contribution_trends", "Funding_overview"],
		apiType: "data",
	},
	{
		apiName: "targetedPersonsData",
		url: "https://cbpfapi.unocha.org/vo2/odata/PoolFundBeneficiarySummary",
		queryString: "?$format=csv&ShowAllPooledFunds=1",
		charts: ["Sectors"],
		apiType: "data",
	},
	{
		apiName: "targetedPersonsDetailsData",
		url: "https://cbpfapi.unocha.org/vo2/odata/ProjectSummaryBeneficiaryDetail",
		queryString: "?$format=csv",
		charts: ["Targeted_and_reached_people"],
		apiType: "data",
	},
	{
		apiName: "dataGam",
		url: "https://cbpfapi.unocha.org/vo2/odata/ProjectGAMSummary",
		queryString: "?$format=csv",
		charts: ["Gender_with_age_marker"],
		apiType: "data",
	},
	{
		apiName: "masterGam",
		url: "https://cbpfapi.unocha.org/vo2/odata/GenderMarker",
		queryString: "?$format=csv",
		charts: ["Gender_with_age_marker"],
		apiType: "master",
	},
	{
		apiName: "masterOrganizations",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstOrganization.json",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "masterSectors",
		url: "https://cbpfgms.github.io/pfbi-data/mst/MstCluster.json",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "allocationsDataResults",
		url: "https://cbpfapi.unocha.org/vo2/odata/AllocationBudgetTotalsByYearAndFund",
		queryString: "?poolfundAbbrv=&$format=csv",
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "resultsBySector",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/ByCluster.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "resultsByDisability",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/ByGender_Disability.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "resultsByType",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/ByLocation.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "resultsByBeneficiaryType",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/ByType.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "resultsByOrganization",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/ByOrganization.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "data",
	},
	{
		apiName: "masterLocations",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/locationMst.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "masterBeneficiaryType",
		url: "https://cbpfgms.github.io/pfbi-data/cbpf/results/MstBeneficiaryType.csv",
		queryString: null,
		charts: ["Results_dashboard"],
		apiType: "master",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
	{
		apiName: "",
		url: "",
		queryString: "",
		charts: [],
		apiType: "data",
	},
] as const;
