const constants = {
	closedStatusNames: ["PRJ_PRJ_CLR", "PRJ_UND_CLSR"],
	implementationStatuses: [
		"Under Implementation",
		"Programmatically Closed",
		"Financially Closed",
	],
	beneficiariesSplitOrder: [3, 5, 6, 2, 4], //IDP|Refugees|Returnees|Host Communities|Others
	pageName: "CBPFProgress",
	localStorageTime: 60 * 60 * 1000, //1 hour
	consoleStyle: "background-color: #0d6cb6; color: white; padding: 2px;",
	isProdSite: window.location.hostname === "cbpf.data.unocha.org",
	charts: [
		"summary",
		"pictogram",
		"beneficiaryTypes",
		"sectors",
		"organizations",
		"disability",
		"gbv",
		"cash",
		"indicators",
	],
	filterTypes: ["Fund", "Year", "Allocation Source", "Allocation Name"],
	beneficiaryCategories: ["women", "girls", "men", "boys"],
	beneficiariesStatuses: ["targeted", "reached"],
	indicatorsHeader: ["indicator", "projects", "targeted", "reached"],
	columnWidths: ["52%", "8%", "20%", "20%"],
	columnWidthsExpanded: ["26%", "6%", "34%", "34%"],
	reportTypes: [0, 1, 2],
	reportsForDisability: [1, 2],
	reportsForGBV: [2],
	finalReportCode: 2,
	yearLabelPadding: 32,

	duration: 750,
	monthsArray: [
		"Jan",
		"Feb",
		"Mar",
		"Apr",
		"May",
		"Jun",
		"Jul",
		"Aug",
		"Sep",
		"Oct",
		"Nov",
		"Dec",
	],
	overviewIconSize: 24,
	overviewIconSizeByGroup: 32,
	overviewGroupScalePaddingInner: 0.4,
	overviewGroupScalePaddingOuter: 0.5,
	overviewAxisWidth: 100,
	overviewAxisByGroupWidth: 110,
	idString: "id_",
	stackGap: 2,
	fullMonthNames: {
		Jan: "January",
		Feb: "February",
		Mar: "March",
		Apr: "April",
		May: "May",
		Jun: "June",
		Jul: "July",
		Aug: "August",
		Sep: "September",
		Oct: "October",
		Nov: "November",
		Dec: "December",
	},
	timelineOpacity: 0.4,
	limitValue: 0.9,
	yearScaleInnerPadding: 0.2,
	yearScaleOuterPadding: 0.35,
	zeroValueOpacity: 0.5,
	yearTimelinePadding: 42,
	paddingHeight: 0, //if padding needed over the area chart
	maxNumberOfYearsOnDisplay: 2,
	iconSize: 30,
	cvaChartModes: ["allocations", "people"],
	cvaChartTypes: [1, 2, 3, 4, 5],
	cvaTopChartColors: {
		1: "#ea5545",
		2: "#ef9b20",
		3: "#87bc45",
		4: "#3e6f8f",
		5: "#b33dc6",
	},
	limitScaleValueInPixels: 90,
	cvaPopoverWidth: 760,
} as const;

export default constants;
